// Code generated by "stringer -type=PlayStatusType"; DO NOT EDIT.

package dispremote

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayStatusStopped-0]
	_ = x[PlayStatusPlaying-1]
	_ = x[PlayStatusPaused-2]
	_ = x[PlayStatusFF-3]
	_ = x[PlayStatusREW-4]
	_ = x[PlayStatusEndFFREW-5]
}

const _PlayStatusType_name = "PlayStatusStoppedPlayStatusPlayingPlayStatusPausedPlayStatusFFPlayStatusREWPlayStatusEndFFREW"

var _PlayStatusType_index = [...]uint8{0, 17, 34, 50, 62, 75, 93}

func (i PlayStatusType) String() string {
	if i >= PlayStatusType(len(_PlayStatusType_index)-1) {
		return "PlayStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayStatusType_name[_PlayStatusType_index[i]:_PlayStatusType_index[i+1]]
}
