// Code generated by "stringer -type=TrackInfoType"; DO NOT EDIT.

package dispremote

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TrackInfoTypeCaps-0]
	_ = x[TrackInfoTypeChapterTimeName-1]
	_ = x[TrackInfoTypeArtist-2]
	_ = x[TrackInfoTypeAlbum-3]
	_ = x[TrackInfoTypeGenre-4]
	_ = x[TrackInfoTypeTrack-5]
	_ = x[TrackInfoTypeComposer-6]
	_ = x[TrackInfoTypeLyrics-7]
	_ = x[TrackInfoTypeArtworkCount-8]
}

const _TrackInfoType_name = "TrackInfoTypeCapsTrackInfoTypeChapterTimeNameTrackInfoTypeArtistTrackInfoTypeAlbumTrackInfoTypeGenreTrackInfoTypeTrackTrackInfoTypeComposerTrackInfoTypeLyricsTrackInfoTypeArtworkCount"

var _TrackInfoType_index = [...]uint8{0, 17, 45, 64, 82, 100, 118, 139, 158, 183}

func (i TrackInfoType) String() string {
	if i >= TrackInfoType(len(_TrackInfoType_index)-1) {
		return "TrackInfoType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TrackInfoType_name[_TrackInfoType_index[i]:_TrackInfoType_index[i+1]]
}
