// Code generated by "stringer -type=AccCapBit"; DO NOT EDIT.

package general

import "strconv"

const (
	_AccCapBit_name_0 = "AccCapAnalogLineOutAccCapAnalogLineIn"
	_AccCapBit_name_1 = "AccCapAnalogVideoOut"
	_AccCapBit_name_2 = "AccCapUSBAudio"
	_AccCapBit_name_3 = "AccCapAppComm"
	_AccCapBit_name_4 = "AccCapCheckVolume"
)

var (
	_AccCapBit_index_0 = [...]uint8{0, 19, 37}
)

func (i AccCapBit) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _AccCapBit_name_0[_AccCapBit_index_0[i]:_AccCapBit_index_0[i+1]]
	case i == 4:
		return _AccCapBit_name_1
	case i == 16:
		return _AccCapBit_name_2
	case i == 512:
		return _AccCapBit_name_3
	case i == 2048:
		return _AccCapBit_name_4
	default:
		return "AccCapBit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
