// Code generated by "stringer -type=AccInfoType"; DO NOT EDIT.

package general

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccInfoName-1]
	_ = x[AccInfoFirmware-4]
	_ = x[AccInfoHardware-5]
	_ = x[AccInfoMfr-6]
	_ = x[AccInfoModel-7]
	_ = x[AccInfoSerial-8]
	_ = x[AccInfoMaxPayload-9]
}

const (
	_AccInfoType_name_0 = "AccInfoName"
	_AccInfoType_name_1 = "AccInfoFirmwareAccInfoHardwareAccInfoMfrAccInfoModelAccInfoSerialAccInfoMaxPayload"
)

var (
	_AccInfoType_index_1 = [...]uint8{0, 15, 30, 40, 52, 65, 82}
)

func (i AccInfoType) String() string {
	switch {
	case i == 1:
		return _AccInfoType_name_0
	case 4 <= i && i <= 9:
		i -= 4
		return _AccInfoType_name_1[_AccInfoType_index_1[i]:_AccInfoType_index_1[i+1]]
	default:
		return "AccInfoType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
