// Code generated by "stringer -type=AccInfoType"; DO NOT EDIT.

package general

import "strconv"

const (
	_AccInfoType_name_0 = "AccInfoName"
	_AccInfoType_name_1 = "AccInfoFirmwareAccInfoHardwareAccInfoMfrAccInfoModelAccInfoSerialAccInfoMaxPayload"
)

var (
	_AccInfoType_index_1 = [...]uint8{0, 15, 30, 40, 52, 65, 82}
)

func (i AccInfoType) String() string {
	switch {
	case i == 1:
		return _AccInfoType_name_0
	case 4 <= i && i <= 9:
		i -= 4
		return _AccInfoType_name_1[_AccInfoType_index_1[i]:_AccInfoType_index_1[i+1]]
	default:
		return "AccInfoType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
