// Code generated by "stringer -type=LingoBit"; DO NOT EDIT.

package general

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LingoGeneralBit-1]
	_ = x[LingoSimpleRemoteBit-4]
	_ = x[LingoDisplayRemoteBit-8]
	_ = x[LingoExtRemoteBit-16]
	_ = x[LingoUSBHostBit-64]
	_ = x[LingoRFTunerBit-128]
	_ = x[LingoEqBit-256]
	_ = x[LingoSportsBit-512]
	_ = x[LingoDigitalAudioBit-1024]
	_ = x[LingoStorageBit-4096]
}

const (
	_LingoBit_name_0 = "LingoGeneralBit"
	_LingoBit_name_1 = "LingoSimpleRemoteBit"
	_LingoBit_name_2 = "LingoDisplayRemoteBit"
	_LingoBit_name_3 = "LingoExtRemoteBit"
	_LingoBit_name_4 = "LingoUSBHostBit"
	_LingoBit_name_5 = "LingoRFTunerBit"
	_LingoBit_name_6 = "LingoEqBit"
	_LingoBit_name_7 = "LingoSportsBit"
	_LingoBit_name_8 = "LingoDigitalAudioBit"
	_LingoBit_name_9 = "LingoStorageBit"
)

func (i LingoBit) String() string {
	switch {
	case i == 1:
		return _LingoBit_name_0
	case i == 4:
		return _LingoBit_name_1
	case i == 8:
		return _LingoBit_name_2
	case i == 16:
		return _LingoBit_name_3
	case i == 64:
		return _LingoBit_name_4
	case i == 128:
		return _LingoBit_name_5
	case i == 256:
		return _LingoBit_name_6
	case i == 512:
		return _LingoBit_name_7
	case i == 1024:
		return _LingoBit_name_8
	case i == 4096:
		return _LingoBit_name_9
	default:
		return "LingoBit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
